name: deploy
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    uses: tolgacelik22/gh-workflows/.github/workflows/build-image.yml@main
    with:
      app: klog
    secrets:
      INFRA_DEPLOY_KEY: ${{ secrets.INFRA_DEPLOY_KEY }}
