name: deploy
on:
  push:
    branches: [rename/nois]
jobs:
  build-deploy:
    permissions:
      contents: read
      packages: write
    uses: tolgacelik22/gh-workflows/.github/workflows/build-image.yml@main
    with:
      app: nois
    secrets:
      INFRA_DEPLOY_KEY: ${{ secrets.INFRA_DEPLOY_KEY }}
